// <auto-generated />
namespace EcommerceOsorioManha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WS_CEP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WS_CEP));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111219344_WS_CEP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
